[package]
name = "foxvoice-engine"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[features]
default = []
windowsml = ["vc-app/windowsml", "vc-core/windowsml"]

[dependencies]
anyhow.workspace = true
claxon = "0.4.3"
cpal.workspace = true
flacenc = { version = "0.5.1", default-features = false }
hound = "3.5.1"
serde.workspace = true
serde_json.workspace = true
symphonia = { version = "0.5.5", features = ["all"] }
vc-app = { path = "../../vendor/vc-app", default-features = false }
vc-core = { git = "https://github.com/shirohata/vc-rs.git", rev = "2c3b57661c4a38f56e64c521a71e65dc68db5895", default-features = false }

[dev-dependencies]
tempfile = "3.23.0"
